#!/usr/bin/env bash
# Build the freestanding wasm32+SIMD blur kernel and embed it as base64 TS.
# Requires an LLVM clang with the wasm32 target + wasm-ld (emscripten bundles
# one). No emscripten runtime is used -- output is a bare WebAssembly module.
set -euo pipefail
cd "$(dirname "$0")"

# Locate a clang that can emit+link wasm (needs wasm-ld on PATH or bundled).
CLANG="${WASM_CLANG:-}"
if [ -z "$CLANG" ]; then
  for c in \
    /opt/homebrew/Cellar/emscripten/*/libexec/llvm/bin/clang \
    "$(command -v clang || true)"; do
    if [ -x "$c" ] && [ -x "$(dirname "$c")/wasm-ld" ]; then CLANG="$c"; break; fi
  done
fi
if [ -z "$CLANG" ]; then echo "no wasm-capable clang (need clang + wasm-ld)"; exit 1; fi
export PATH="$(dirname "$CLANG"):$PATH"
echo "using clang: $CLANG"

"$CLANG" --target=wasm32 -O3 -msimd128 -nostdlib \
  -Wl,--no-entry -Wl,--export-dynamic -Wl,--export=__heap_base \
  -Wl,--initial-memory=1048576 -Wl,--max-memory=536870912 \
  -o blur.wasm blur.c

BYTES=$(wc -c < blur.wasm | tr -d ' ')
echo "blur.wasm: ${BYTES} bytes"

# Embed as base64 in a TS module (CSP-safe, no runtime fetch).
B64=$(base64 < blur.wasm | tr -d '\n')
cat > wasm-bytes.ts <<EOF
// AUTO-GENERATED by build.sh from blur.c. Do not edit by hand.
// Freestanding wasm32+SIMD level-0 gaussian blur, base64-embedded.
export const BLUR_WASM_BASE64 =
  "${B64}";
EOF
echo "wrote wasm-bytes.ts (${#B64} b64 chars)"
