import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const result = await Bun.build({
  entrypoints: [join(ROOT, "src/core/worker-entry.ts")],
  target: "browser",
  format: "esm",
  minify: true,
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("worker-entry inline bundle failed");
}

const code = await result.outputs[0]!.text();
const body =
  "// Generated by tools/build-inline-worker.ts. Do not edit by hand.\n" +
  `export const INLINED_WORKER_CODE: string | null = ${JSON.stringify(code)};\n`;

writeFileSync(join(ROOT, "src/generated/worker-inline.ts"), body);
console.log(`inline worker: ${(code.length / 1024).toFixed(1)} KiB`);
